export const experiences = [
    {
        id: 1,
        title: "World Nomad Games",
        location: "Kyrgyzstan",
        country: "Kyrgyzstan",
        image: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&h=600&fit=crop",
        category: "Culture",
        region: "asia",
        year: "2026",
        savedCount: 4521,
        difficulty: "moderate",
        bestTime: "September (during the games)",
        budget: "$1,500 - $2,500 for 1 week",
        tips: "Book accommodation in Cholpon-Ata early — it sells out fast during the games.",
    },
    {
        id: 2,
        title: "Northern Lights Safari",
        location: "Tromsø, Norway",
        country: "Norway",
        image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=600&fit=crop",
        category: "Nature",
        region: "europe",
        savedCount: 12893,
        difficulty: "easy",
        bestTime: "September to March",
        budget: "$2,000 - $3,500 for 5 days",
        tips: "Stay at least 3 nights to maximize your chances of clear skies.",
    },
    {
        id: 3,
        title: "Cherry Blossom Season",
        location: "Kyoto, Japan",
        country: "Japan",
        image: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&h=600&fit=crop",
        category: "Nature",
        region: "asia",
        savedCount: 18234,
        difficulty: "easy",
        bestTime: "Late March to early April",
        budget: "$2,500 - $4,000 for 1 week",
        tips: "Visit Maruyama Park at night for stunning illuminated blossoms.",
    },
    {
        id: 4,
        title: "Carnival of Venice",
        location: "Venice, Italy",
        country: "Italy",
        image: "https://images.unsplash.com/photo-1518730518541-d0843268c287?w=800&h=600&fit=crop",
        category: "Festivals",
        region: "europe",
        savedCount: 8456,
        difficulty: "easy",
        bestTime: "February (dates vary yearly)",
        budget: "$3,000 - $5,000 for 5 days",
        tips: "Rent a costume from a local atelier for an authentic experience.",
    },
    {
        id: 5,
        title: "Machu Picchu Sunrise",
        location: "Cusco, Peru",
        country: "Peru",
        image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&h=600&fit=crop",
        category: "Adventure",
        region: "americas",
        savedCount: 21567,
        difficulty: "moderate",
        bestTime: "April to October (dry season)",
        budget: "$1,800 - $3,000 for 1 week",
        tips: "Take the 4-day Inca Trail hike for the most rewarding approach.",
    },
    {
        id: 6,
        title: "Street Food Markets",
        location: "Bangkok, Thailand",
        country: "Thailand",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop",
        category: "Food",
        region: "asia",
        savedCount: 15678,
        difficulty: "easy",
        bestTime: "November to February (cool season)",
        budget: "$800 - $1,500 for 1 week",
        tips: "Join a food tour your first night to learn what to order.",
    },
    {
        id: 7,
        title: "Hot Air Balloons",
        location: "Cappadocia, Turkey",
        country: "Turkey",
        image: "https://images.unsplash.com/photo-1507501336603-6e31db2be093?w=800&h=600&fit=crop",
        category: "Adventure",
        region: "asia",
        savedCount: 19234,
        difficulty: "easy",
        bestTime: "April to October",
        budget: "$1,200 - $2,000 for 4 days",
        tips: "Book your balloon ride for the first morning — weather cancellations are common.",
    },
    {
        id: 8,
        title: "Santorini Sunset",
        location: "Oia, Greece",
        country: "Greece",
        image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=600&fit=crop",
        category: "Nature",
        region: "europe",
        savedCount: 24567,
        difficulty: "easy",
        bestTime: "April to June, September to October",
        budget: "$2,500 - $4,500 for 5 days",
        tips: "Skip Oia's crowded castle — watch from a restaurant terrace with wine instead.",
    },
    {
        id: 9,
        title: "Holi Festival",
        location: "Jaipur, India",
        country: "India",
        image: "https://images.unsplash.com/photo-1576089073624-b5751a8f4de9?w=800&h=600&fit=crop",
        category: "Festivals",
        region: "asia",
        savedCount: 11234,
        difficulty: "moderate",
        bestTime: "March (date varies yearly)",
        budget: "$1,000 - $2,000 for 1 week",
        tips: "Wear old white clothes and apply coconut oil to skin before celebrating.",
    },
    {
        id: 10,
        title: "Safari at Dawn",
        location: "Serengeti, Tanzania",
        country: "Tanzania",
        image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&h=600&fit=crop",
        category: "Adventure",
        region: "africa",
        savedCount: 16789,
        difficulty: "bucket-list",
        bestTime: "June to October (Great Migration)",
        budget: "$5,000 - $10,000 for 1 week",
        tips: "The Northern Serengeti offers fewer crowds and river crossings.",
    },
    {
        id: 11,
        title: "Ice Hotel Stay",
        location: "Jukkasjärvi, Sweden",
        country: "Sweden",
        image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop",
        category: "Wellness",
        region: "europe",
        savedCount: 7823,
        difficulty: "easy",
        bestTime: "December to April",
        budget: "$800 - $1,500 for 2 nights",
        tips: "Book an art suite for the most impressive ice sculptures.",
    },
    {
        id: 12,
        title: "Great Wall Hike",
        location: "Beijing, China",
        country: "China",
        image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop",
        category: "Adventure",
        region: "asia",
        savedCount: 14567,
        difficulty: "moderate",
        bestTime: "April to May, September to October",
        budget: "$1,500 - $2,500 for 1 week",
        tips: "Hike the unrestored Jiankou section for authentic, uncrowded views.",
    },
    {
        id: 13,
        title: "Great Barrier Reef Diving",
        location: "Queensland, Australia",
        country: "Australia",
        image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=800&h=600&fit=crop",
        category: "Adventure",
        region: "oceania",
        savedCount: 13456,
        difficulty: "moderate",
        bestTime: "June to October",
        budget: "$3,000 - $5,000 for 1 week",
        tips: "Take a liveaboard trip to reach the outer reef with better visibility.",
    },
    {
        id: 14,
        title: "Milford Sound Cruise",
        location: "Fiordland, New Zealand",
        country: "New Zealand",
        image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&h=600&fit=crop",
        category: "Nature",
        region: "oceania",
        savedCount: 9876,
        difficulty: "easy",
        bestTime: "December to February",
        budget: "$2,500 - $4,000 for 1 week",
        tips: "Rain actually enhances the experience with hundreds of temporary waterfalls.",
    },
];
